### ISSUE TITLE
SOCI CLI integration test expansion

### ISSUE THREAD

**Issue by Kern--** [awslabs/soci-snapshotter#54]
**Is your feature request related to a problem? Please describe.**
The SOCI CLI is tested for integration around the core user experience of creating/pushing/pulling SOCI indices, but it is not tested around the debug tooling for indices and ztocs. We should add integration tests to verify these debugging tools.

**Describe the solution you'd like**
The following integration tests:
- [x] `index list` #250
- [x] `index list` with image ref #250
- [x] `index info` #250
- [x] `ztoc list` #265
- [x] `ztoc list` with digest #265
- [x] `ztoc info` #334 
- [x] `ztoc get-file` #334 
- [x] `index rm` with digest #260 
- [x] `index rm` with image ref #260
- [x] `index rm` everything #260
- [ ] `create` with all platforms
- [ ] `push` with all platforms
- [ ] `image rpull` with all platforms

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rdpsin** [comment]
Additionally, 

- `index rm`
- `index rm` with image ref
-  `index rm` everything.

**Comment by djdongjin** [comment]
@rdpsin @Kern-- do we still miss tests for this three in the list

- [ ]  `create` with all platforms
- [ ] `push` with all platforms
- [ ] `image rpull` with all platforms

for 1, we have https://github.com/awslabs/soci-snapshotter/blob/main/integration/create_test.go#L168

for 2 and 3, we have https://github.com/awslabs/soci-snapshotter/blob/main/integration/push_test.go#L74-L86

not sure if they cover the `all platforms`; if not, any other platforms we want to add?

**Comment by djdongjin** [comment]
Closing this one since all tests are added/exists.

We have multi platform tests linked in the comments above: https://github.com/awslabs/soci-snapshotter/issues/54#issuecomment-1362948399

@Kern-- lmk if there's something not covered.
