### ISSUE TITLE
Tracking Issue: Registry Operations

### ISSUE THREAD

**Issue by turan18** [awslabs/soci-snapshotter#904]
### Description

This issue is meant to serve as a tracking issue for refactors/bug fixes/optimizations pertaining to remote registry operations.

```[tasklist]
### Tasks 
- [ ] Design unified HTTP client: #759 
- [ ] Implement unified HTTP client
- [ ] Fix blob resolver extra redirection: #655 
- [ ] Multi-cred support when fetching artifacts: #903
- [ ] Separate span size from download size: #534 
```
