### ISSUE TITLE
[FEATURE] Run GitHub workflows when the workflows change

### ISSUE THREAD

**Issue by austinvazquez** [awslabs/soci-snapshotter#911]
### Description

As part of #910, I noticed the build workflow did not run due to conditional skips. As a maintainer, it would be helpful for the workflows to run when the workflows themselves change for validation.

### Describe the solution you'd like

The following conditions to be added to the respective workflows:

Benchmark workflow:
- SHOULD run when benchmarks when the benchmark workflow is changed.
- SHOULD run when benchmarks when benchmarks are added or changed.
- SHOULD NOT post results to benchmark website on pull request runs.

Build workflow:
- SHOULD run when build workflow is changed.

Comparison test workflow:
- SHOULD run when comparison test workflow is changed.
- SHOULD run when comparison test benchmark is changed.

Release workflow
- SHOULD run when release workflow is changed. (using a test release tag)
- SHOULD NOT create a release on pull request runs.

```[tasklist]
### Tasks
- [x] Run build workflows on change
- [x] Run release workflow on change
- [ ] Run benchmark workflow on change
```

**Comment by sondavidb** [comment]
#1186 runs release workflows when they're changed. I think we still need something to run benchmarks when those workflows change, since it looks like they currently only run on commit [push](https://github.com/awslabs/soci-snapshotter/blob/739c04f167b63b334e6cdae4486cabe8b17f69a7/.github/workflows/benchmark_visualization.yml#L4)
